# Generated by Django 5.1.6 on 2025-03-05 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, verbose_name="почта")),
                ("country", models.CharField(max_length=30, verbose_name="страна")),
                ("city", models.CharField(max_length=50, verbose_name="город")),
                ("street", models.CharField(max_length=100, verbose_name="улица")),
                ("house_number", models.CharField(max_length=10, verbose_name="номер дома")),
            ],
            options={
                "verbose_name": "контакт сети",
                "verbose_name_plural": "контакты сети",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="название")),
                ("model", models.CharField(max_length=100, verbose_name="модель")),
                ("release_date", models.DateField(verbose_name="дата выхода продукта на рынок")),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.CreateModel(
            name="NetMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="название сети")),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(0, "Завод"), (1, "Розничная сеть"), (2, "Индивидуальный предприниматель")],
                        default=0,
                        verbose_name="уровень иерархии",
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=15, verbose_name="задолженность перед поставщиком"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="время создания")),
                (
                    "contacts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netmember",
                        to="net.contact",
                        verbose_name="контакт",
                    ),
                ),
                (
                    "suplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="net.netmember",
                        verbose_name="поставщик",
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="net.product", verbose_name="продукты"
                    ),
                ),
            ],
            options={
                "verbose_name": "звено сети",
                "verbose_name_plural": "звенья сети",
            },
        ),
    ]
