# Generated by Django 5.1.6 on 2025-03-05 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("net", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="netmember",
            name="contacts",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="netmember",
                to="net.contact",
                verbose_name="контакт",
            ),
        ),
        migrations.AlterField(
            model_name="netmember",
            name="products",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="net.product",
                verbose_name="продукты",
            ),
        ),
    ]
