# Generated by Django 5.1.6 on 2025-03-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("net", "0002_alter_netmember_contacts_alter_netmember_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="netmember",
            name="products",
        ),
        migrations.AddField(
            model_name="netmember",
            name="products",
            field=models.ManyToManyField(blank=True, null=True, to="net.product", verbose_name="продукты"),
        ),
    ]
