# Generated by Django 5.1.6 on 2025-03-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("net", "0003_remove_netmember_products_netmember_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="netmember",
            name="products",
            field=models.ManyToManyField(to="net.product", verbose_name="продукты"),
        ),
    ]
